# Generated by Django 4.1.1 on 2022-09-14 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='resolution_height',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='map',
            name='resolution_width',
            field=models.IntegerField(null=True),
        ),
    ]
