# Generated by Django 4.1.1 on 2022-09-07 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='image',
            field=models.ImageField(null=True, upload_to='locations/'),
        ),
        migrations.AddField(
            model_name='location',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='locations/thumbnails/'),
        ),
    ]
