# Generated by Django 4.1.1 on 2022-10-04 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_map_resolution_height_map_resolution_width'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map',
            name='is_active',
        ),
    ]
