# Generated by Django 4.1.1 on 2022-10-04 14:46

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_remove_map_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='vector_column',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='map',
            index=django.contrib.postgres.indexes.GinIndex(fields=['vector_column'], name='maps_map_vector__ba181f_gin'),
        ),
    ]
