# Generated by Django 4.1.1 on 2022-10-04 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0004_map_vector_column_map_maps_map_vector__ba181f_gin'),
    ]

    operations = [
        migrations.RunSQL(
            sql='''
              CREATE TRIGGER vector_column_trigger
              BEFORE INSERT OR UPDATE OF name, description, vector_column
              ON maps_map
              FOR EACH ROW EXECUTE PROCEDURE
              tsvector_update_trigger(
                vector_column, 'pg_catalog.english', name, description
              );

              UPDATE maps_map SET vector_column = NULL;
            ''',

            reverse_sql='''
              DROP TRIGGER IF EXISTS vector_column_trigger
              ON maps_map;
            '''
        ),
    ]
