# Generated by Django 4.1.1 on 2022-10-11 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0005_create_trigger'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='map',
            index=models.Index(fields=['name'], name='maps_map_name_c173ad_idx'),
        ),
    ]
