repos:
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        exclude: ^.*\b(migrations)\b.*$
        language_version: python3.10
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        exclude: ^.*\b(migrations)\b.*$
        args: ["--profile", "black", "--filter-files"]
        files: \.py$
  - repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    - id: flake8
      args: ['--config=setup.cfg']
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: check-django-migrations
        name: Check django migrations
        entry: docker-compose -f docker-compose.yml run web python3 manage.py makemigrations --dry-run --check
        language: system
        types: [ python ] # hook only runs if a python file is staged
        pass_filenames: false
