# Generated by Django 3.2.13 on 2022-07-05 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='players',
        ),
    ]
