# Generated by Django 4.1.1 on 2022-10-03 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='is_active',
        ),
    ]
