# Generated by Django 4.1.1 on 2022-10-03 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_remove_campaign_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='invite_code',
            field=models.UUIDField(null=True, unique=True),
        ),
    ]
