# Generated by Django 4.1.1 on 2022-10-04 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_campaign_vector_column_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql='''
              CREATE TRIGGER vector_column_trigger
              BEFORE INSERT OR UPDATE OF name, description, vector_column
              ON campaigns_campaign
              FOR EACH ROW EXECUTE PROCEDURE
              tsvector_update_trigger(
                vector_column, 'pg_catalog.english', name, description
              );

              UPDATE campaigns_campaign SET vector_column = NULL;
            ''',

            reverse_sql='''
              DROP TRIGGER IF EXISTS vector_column_trigger
              ON campaigns_campaign;
            '''
        ),
    ]
