# Generated by Django 4.1.1 on 2022-10-11 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_generated_columns'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['name'], name='campaigns_c_name_602631_idx'),
        ),
    ]
