# Generated by Django 4.1.1 on 2022-10-14 19:03

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0007_campaign_campaigns_c_name_602631_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='description',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
