# Generated by Django 4.1.1 on 2022-09-30 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='is_npc',
            field=models.BooleanField(default=False),
        ),
    ]
