# Generated by Django 4.1.1 on 2022-10-04 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0004_alter_character_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='is_active',
        ),
    ]
