# Generated by Django 4.1.1 on 2022-10-04 14:46

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0005_remove_character_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='vector_column',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='character',
            index=django.contrib.postgres.indexes.GinIndex(fields=['vector_column'], name='characters__vector__7e8e22_gin'),
        ),
    ]
