# Generated by Django 4.1.1 on 2022-10-05 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0007_create_trigger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='creator',
        ),
    ]
