# Generated by Django 4.1.1 on 2022-10-11 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0008_remove_character_creator'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='character',
            index=models.Index(fields=['name'], name='characters__name_6d8b81_idx'),
        ),
    ]
