# Generated by Django 4.1.1 on 2022-10-14 21:06

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0009_character_characters__name_6d8b81_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='description',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
