# Generated by Django 4.1.4 on 2022-12-18 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0012_alter_character_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='location',
        ),
    ]
