# Generated by Django 4.1.1 on 2022-09-14 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='image',
        ),
        migrations.RemoveField(
            model_name='location',
            name='thumbnail',
        ),
    ]
