# Generated by Django 4.1.1 on 2022-10-11 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_remove_location_image_remove_location_thumbnail'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['name'], name='locations_l_name_0dcc82_idx'),
        ),
    ]
