# Generated by Django 4.1.1 on 2022-10-14 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_location_locations_l_name_0dcc82_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='image',
            field=models.ImageField(null=True, upload_to='locations/'),
        ),
    ]
