# Generated by Django 4.1.1 on 2022-10-19 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_alter_location_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ('-created',), 'verbose_name': 'Location', 'verbose_name_plural': 'Locations'},
        ),
    ]
