# Generated by Django 4.1.1 on 2022-10-19 11:38

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0007_alter_location_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='vector_column',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='location',
            index=django.contrib.postgres.indexes.GinIndex(fields=['vector_column'], name='locations_l_vector__ec70fc_gin'),
        ),
    ]
