# Generated by Django 4.1.1 on 2022-10-25 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0009_create_trigger'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ('order',), 'verbose_name': 'Location', 'verbose_name_plural': 'Locations'},
        ),
        migrations.AddField(
            model_name='location',
            name='order',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
