# Generated by Django 4.1.4 on 2022-12-17 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0011_location_hidden'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Location', 'verbose_name_plural': 'Locations'},
        ),
        migrations.RemoveField(
            model_name='location',
            name='order',
        ),
    ]
