# Generated by Django 4.1.1 on 2022-10-10 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_create',
            field=models.BooleanField(default=False),
        ),
    ]
